---

keybinds:
    unbind: true
    normal:
        - action: [Detach,]
          key: [Ctrl: 'Q',]
        - action: [NewPane: Right ]
          key: [Ctrl: 'n',]
        - action: [NewPane: Down ]
          key: [Ctrl: 't',]          
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'Left',]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'Right',]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'Down',]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'Up',]          
        - action: [FocusPreviousPane,]
          key: [ Alt: '[',]
        - action: [FocusNextPane,]
          key: [ Alt: ']',]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [MovePane: ,]
          key: [ Alt: 'm', ]          
 


plugins:
  - path: tab-bar
    tag: tab-bar
  - path: status-bar
    tag: status-bar
  - path: strider
    tag: strider

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
on_force_close: detach

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
#default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# Default: default
#theme: default

# Choose the mode that zellij uses when starting up.
# Default: normal
#default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
#mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
#scroll_buffer_size: 10000
