export CONFIG_HOME="$HOME/.config/" 
export CUSTOM_DOTFILES_HOME="$CONFIG_HOME/dotfiles/zsh" 

source "$CUSTOM_DOTFILES_HOME/functions.zsh"
source "$CUSTOM_DOTFILES_HOME/envs.zsh"
source "$CUSTOM_DOTFILES_HOME/plugins.zsh"
source "$CUSTOM_DOTFILES_HOME/loaders.zsh"
source "$CUSTOM_DOTFILES_HOME/paths.zsh"
source "$CUSTOM_DOTFILES_HOME/alias.zsh"
source "$CUSTOM_DOTFILES_HOME/p10k.zsh"
source "$CUSTOM_DOTFILES_HOME/bindkeys.zsh"
